version: "3.8"

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  geocode:
    image: "mediagis/nominatim:4.3⁠"
    ports:
      - "8080:8080"
    environment:
      NOMINATIM_PBF_URL: "https://download.geofabrik.de/europe/france-latest.osm.pbf"
      NOMINATIM_PBF_MD5_URL: "https://download.geofabrik.de/europe/france-latest.osm.pbf.md5"
volumes:
  redis-data:
